### ISSUE TITLE
Maintainers?

### ISSUE THREAD

**Issue by lextiz** [petkaantonov/bluebird-q#10]
Hello @petkaantonov. Thanks for great library and the bluebird-q shim! Do you plan to maintain this repository? If you do not have enough time to do this could you consider to add additional contributors to this repository?

**Comment by petkaantonov** [comment]
Do you want to maintain it?

**Comment by lextiz** [comment]
I would be happy to contribute by doing code review for bug fixes PRs and connecting this repo to CI. Of course this would be limited by my free time. If you would offer, I would like to be added as contributor to this repo.

**Comment by petkaantonov** [comment]
I have added you as collaborator

**Comment by lextiz** [comment]
Thanks!
