### ISSUE TITLE
Publish 2.0.1 to npm

### ISSUE THREAD

**Issue by Redsandro** [petkaantonov/bluebird-q#17]
Could you publish 2.0 to npm?

**Comment by lextiz** [comment]
I do not have access to @petkaantonov account on npm. @petkaantonov Do you find it appropriate to publish this on npm?

**Comment by lextiz** [comment]
You can reference this library from package.json as archive URL: https://github.com/petkaantonov/bluebird-q/archive/v2.0.1.zip or as a commit in git repository: git://github.com/petkaantonov/bluebird-q.git#c11050c13b977482c7386b175ab24dece5de901e. For more info see: https://docs.npmjs.com/files/package.json#dependencies. Does this solve your issue?

**Comment by petkaantonov** [comment]
@lextiz  I could add you as owner?

**Comment by lextiz** [comment]
No problem, thanks!

**Comment by petkaantonov** [comment]
I need your npm username and email

**Comment by petkaantonov** [comment]
It will allow you to do `npm publish ./` to publish bluebird-q

**Comment by lextiz** [comment]
username: lextiz, email: lextiz _at_ gmail.com

**Comment by lextiz** [comment]
Thanks! Will publish soon.

**Comment by petkaantonov** [comment]
ok you can now publish (though I just published 2.0.1)

**Comment by Redsandro** [comment]
Thanks everyone :+1:
