### ISSUE TITLE
q-spec doesn't get run (and when you run it, it fails)

### ISSUE THREAD

**Issue by mvayngrib** [petkaantonov/bluebird-q#22]
first, thanks for the module! Now onto my issue...

because q is not in devDependencies, npm test will silently (!) crash on line 28 of spec/q-spec.js:

```js
var Q = require("q");
```

if you `npm install q@^1`, you'll see that lots of tests in q-spec.js actually fail

**Comment by lextiz** [comment]
Hi @mvayngrib, thanks for the report. There were multiple problems, some will be solved, see https://github.com/petkaantonov/bluebird-q/pull/23 for details, now it is pending for review.

**Comment by mvayngrib** [comment]
@lextiz awesome, thanks for the quick response :)

**Comment by lextiz** [comment]
Partially solved by https://github.com/petkaantonov/bluebird-q/pull/23
